SELECT LGR.ORG_ID
            , LGR.CUSTOMER_ID
            , CUST.CUSTOMER_NUMBER
            , CUST.CUSTOMER_NAME
            , CUST.CUSTOMER_CLASS_CODE
            , MAX(CURR_SR_ID) CURR_SR_ID
            , MAX(CURR_SR_NAME) CURR_SR_NAME
            , MAX(LGR.LAST_RCV_DATE) LAST_RCV_DATE
            , MAX(LGR.LAST_RCV_DATE_SPAN) LAST_RCV_DATE_SPAN
            , SUM(LGR.DUE_TOTAL_AMT) DUE_TOTAL_AMT
            , CASE WHEN MAX(LGR.LAST_RCV_DATE_SPAN) BETWEEN 1 AND 45 THEN SUM(LGR.DUE_TOTAL_AMT) ELSE 0 END DUE_00_45_MON_AMT
            , CASE WHEN MAX(LGR.LAST_RCV_DATE_SPAN) BETWEEN 46 AND 90 THEN SUM(LGR.DUE_TOTAL_AMT) ELSE 0 END DUE_46_90_MON_AMT
            , CASE WHEN MAX(LGR.LAST_RCV_DATE_SPAN) BETWEEN 91 AND 120 THEN SUM(LGR.DUE_TOTAL_AMT) ELSE 0 END DUE_91_120_MON_AMT
            , CASE WHEN MAX(LGR.LAST_RCV_DATE_SPAN) BETWEEN 121 AND 180 THEN SUM(LGR.DUE_TOTAL_AMT) ELSE 0 END DUE_121_180_MON_AMT
            , CASE WHEN MAX(LGR.LAST_RCV_DATE_SPAN) BETWEEN 181 AND 270 THEN SUM(LGR.DUE_TOTAL_AMT) ELSE 0 END DUE_181_270_MON_AMT
            , CASE WHEN MAX(LGR.LAST_RCV_DATE_SPAN) BETWEEN 271 AND 365 THEN SUM(LGR.DUE_TOTAL_AMT) ELSE 0 END DUE_271_365_MON_AMT
            , CASE WHEN MAX(LGR.LAST_RCV_DATE_SPAN) > 366 THEN SUM(LGR.DUE_TOTAL_AMT) ELSE 0 END DUE_366_PLUS_MON_AMT
        FROM 
            (                    
               SELECT LGR.ORG_ID
                    , LGR.SALES_PERSON_ID
                    , SR.RESOURCE_NAME
                    , LGR.CUSTOMER_ID
                    , LGR.DR_AMOUNT
                    , LGR.CR_AMOUNT
                    , LGR.GL_DATE
                    , MIN(GL_DATE) OVER (PARTITION BY CUSTOMER_ID) FIRST_TRANS_DATE
                    , MAX( CASE WHEN CR_AMOUNT>0 THEN GL_DATE ELSE NULL END) OVER (PARTITION BY CUSTOMER_ID) LAST_RCV_DATE
                    , TO_DATE ( :P_ASONDATE, 'DD-MON-RRRR') 
                            - NVL( MAX( CASE WHEN CR_AMOUNT>0 THEN GL_DATE ELSE NULL END) OVER (PARTITION BY CUSTOMER_ID) 
                                , MIN(GL_DATE) OVER (PARTITION BY CUSTOMER_ID) )
                                LAST_RCV_DATE_SPAN
                    , CASE WHEN LGR.GL_DATE <= TO_DATE ( :P_ASONDATE, 'DD-MON-RRRR') THEN (LGR.DR_AMOUNT-LGR.CR_AMOUNT) ELSE 0 END DUE_TOTAL_AMT
                    , CASE WHEN GL_DATE=MAX(GL_DATE) OVER (PARTITION BY CUSTOMER_ID) THEN LGR.SALES_PERSON_ID ELSE NULL END CURR_SR_ID
                    , CASE WHEN GL_DATE=MAX(GL_DATE) OVER (PARTITION BY CUSTOMER_ID) THEN SR.RESOURCE_NAME ELSE NULL END CURR_SR_NAME
                FROM XX_AR_CUSTOMER_DTL_LEDGER_V LGR
                    , XX_SALESREP_NAME_V SR
                WHERE 1=1
                AND LGR.ORG_ID = SR.ORG_ID(+)
                    AND NVL(LGR.SALES_PERSON_ID,9) = SR.SALESREP_ID(+)
                AND ( LGR.ORG_ID = :P_ORG_ID OR :P_ORG_ID IS NULL )
                AND ( LGR.CUSTOMER_ID = :P_CUSTOMER_ID OR :P_CUSTOMER_ID IS NULL )
                AND LGR.GL_DATE <= NVL ( :P_ASONDATE, TRUNC (SYSDATE))
               -- AND LGR.CUSTOMER_ID IN (470112, 1418, 523433, 470331, 1941, 1187)
            ) LGR
            , XX_AR_CUSTOMERS_ALL_V CUST
        WHERE LGR.CUSTOMER_ID = CUST.CUSTOMER_ID
        GROUP BY LGR.ORG_ID
            , LGR.CUSTOMER_ID
            , CUST.CUSTOMER_NUMBER
            , CUST.CUSTOMER_NAME
            , CUST.CUSTOMER_CLASS_CODE
        HAVING SUM(LGR.DUE_TOTAL_AMT) >0;