SELECT A.SUPPLIER_NUMBER, A.SUPPLIER_NAME, NVL(B.PO_NUMBER,A.PO_NUMBER) PO_NO,
A.LC_ID, A.LC_NUMBER, TRUNC(LC_OPENING_DATE) LC_OPENING_DATE,
(SELECT LISTAGG(RECEIPT_NUM, ', ') WITHIN GROUP (ORDER BY RECEIPT_NUM)
FROM (SELECT RECEIPT_NUM,RSL.PO_HEADER_ID
FROM RCV_SHIPMENT_HEADERS RSH,RCV_SHIPMENT_LINES RSL
 WHERE   RSH.SHIPMENT_HEADER_ID = RSL.SHIPMENT_HEADER_ID --and rownum=1
  GROUP BY RECEIPT_NUM,RSL.PO_HEADER_ID)
  WHERE PO_HEADER_ID = B.PO_HEADER_ID)MRR_NUM,
(SELECT LISTAGG(LOT_NO, ', ') WITHIN GROUP (ORDER BY LOT_NO)
FROM (SELECT NVL (RSH.SHIPMENT_NUM, RSH.BILL_OF_LADING) LOT_NO,PO_HEADER_ID
FROM RCV_SHIPMENT_HEADERS RSH,RCV_SHIPMENT_LINES RSL
 WHERE   RSH.SHIPMENT_HEADER_ID = RSL.SHIPMENT_HEADER_ID
GROUP BY NVL (RSH.SHIPMENT_NUM, RSH.BILL_OF_LADING),PO_HEADER_ID)
WHERE PO_HEADER_ID = B.PO_HEADER_ID) LOT_NUM
FROM XX_LC_DETAILS A, XXPODETAILSSFL B
WHERE A.LC_ID(+) = B.LC_ID
AND A.ORG_ID(+) = B.ORG_ID
AND (:P_PO IS NULL OR B.PO_NUMBER = :P_PO)
AND A.VENDOR_ID BETWEEN NVL(:P_SUPPLIER,A.VENDOR_ID) AND NVL(:P_SUPPLIER,A.VENDOR_ID)
AND TRUNC (B.CREATION_DATE) BETWEEN NVL ( :P_F_DT, TRUNC ( B.CREATION_DATE)) AND NVL ( :P_T_DT, TRUNC (B.CREATION_DATE))
AND A.ORG_ID = 105
ORDER BY A.CREATION_DATE DESC;
/
-------------------------------------after separte
SELECT DISTINCT
    A.SUPPLIER_NUMBER, 
    A.SUPPLIER_NAME, 
    NVL(B.PO_NUMBER, A.PO_NUMBER) AS PO_NO,
    A.LC_ID, 
    A.LC_NUMBER, 
    TRUNC(A.LC_OPENING_DATE) AS LC_OPENING_DATE,
    RECEIPT_NUM MRR_NUM,
    NVL (RSH.SHIPMENT_NUM, RSH.BILL_OF_LADING) LOT_NUM,
    RSL.PO_HEADER_ID,
    A.CREATION_DATE
FROM 
    XX_LC_DETAILS A,
    XXPODETAILSSFL B,
    RCV_SHIPMENT_HEADERS RSH, 
    RCV_SHIPMENT_LINES RSL
WHERE 
    A.LC_ID = B.LC_ID(+) 
    AND B.PO_HEADER_ID = RSL.PO_HEADER_ID
    AND RSH.SHIPMENT_HEADER_ID = RSL.SHIPMENT_HEADER_ID
    AND A.ORG_ID = 105
    AND (:P_PO IS NULL OR B.PO_NUMBER = :P_PO)
    AND A.VENDOR_ID BETWEEN NVL(:P_SUPPLIER, A.VENDOR_ID) AND NVL(:P_SUPPLIER, A.VENDOR_ID)
    AND TRUNC(B.CREATION_DATE) BETWEEN NVL(:P_F_DT, TRUNC(B.CREATION_DATE)) AND NVL(:P_T_DT, TRUNC(B.CREATION_DATE))
ORDER BY 
    A.CREATION_DATE DESC;
/