SELECT DISTINCT
MSI.CONCATENATED_SEGMENTS "Item Code",
MSI.description "Item Name",
MSI.PRIMARY_UNIT_OF_MEASURE "UOM",
QPLL.OPERAND AS "LIST PRICE/ LOCK PRICE"
FROM MTL_SYSTEM_ITEMS_KFV MSI,
QP_LIST_HEADERS_B QLH_B,
QP_LIST_HEADERS_TL QLH_TL,
QP_LIST_LINES QPLL
WHERE QLH_B.LIST_HEADER_ID = QPLL.LIST_HEADER_ID
AND QLH_B.LIST_HEADER_ID = QLH_TL.LIST_HEADER_ID
AND (upper(MSI.attribute10) = upper(:P_MOTHER_CATEGORY) OR :P_MOTHER_CATEGORY IS NULL)
AND QPLL.OPERAND IS NULL
order by 1 asc;