  SELECT DISTINCT
         HOU.NAME AS "ORGANIZATION NAME",
         PHA.SEGMENT1 AS "PO NUMBER",
         MSIK.concatenated_segments AS "ITEM CODE",
         MSIK.INVENTORY_ITEM_ID AS "ITEM ID",
         PLA.ITEM_DESCRIPTION AS "ITEM DESCRIPTION",
         MSIK.PRIMARY_UNIT_OF_MEASURE||' ('||MSIK.PRIMARY_UOM_CODE||')' AS "UOM",
         PLA.QUANTITY AS "PO QTY",
         PHA.CURRENCY_CODE||' '||ROUND(NVL (PLA.UNIT_PRICE, 0),2) AS "ITEM RATE",
         PHA.CURRENCY_CODE||' '||ROUND (NVL (PLA.UNIT_PRICE, 0) * NVL (PLA.QUANTITY, 0)) AS "PO VALUE",
         RT.QUANTITY AS "MRR/GRN QTY",
         AIA.INVOICE_NUM AS "INVOICE NUMBER",
        NVL (AILA.QUANTITY_INVOICED, 0) AS "INVOICE QTY",
        AIA.INVOICE_CURRENCY_CODE||' '||NVL (AILA.AMOUNT, 0) AS "INVOICE AMOUNT",
         ACA.DOC_SEQUENCE_VALUE AS "VOUCHER NO",
         PHA.AUTHORIZATION_STATUS AS "PO STATUS",
         AIA.PAYMENT_CURRENCY_CODE||' '||AIPA.AMOUNT AS "PAYMENT AMOUNT",
         FU.USER_NAME AS "CREATED BY"
       ,  AIDA.LAST_UPDATE_DATE AS "DATE"
    FROM PO_HEADERS_ALL              PHA,
         PO_LINES_ALL                PLA,
         PO_LINE_LOCATIONS_ALL       PLLA,
         PO_DISTRIBUTIONS_ALL        PDA,
         RCV_TRANSACTIONS            RT,
         AP_INVOICE_DISTRIBUTIONS_ALL AIDA,
         AP_INVOICE_LINES_ALL        AILA,
         AP_INVOICES_ALL             AIA,
         AP_INVOICE_PAYMENTS_ALL     AIPA,
         AP_CHECKS_ALL               ACA,
         FND_USER                    FU,
         MTL_SYSTEM_ITEMS_KFV MSIK,
         HR_OPERATING_UNITS HOU
   WHERE     PHA.PO_HEADER_ID = PLA.PO_HEADER_ID
         AND PLLA.PO_LINE_ID = PLA.PO_LINE_ID
         AND PDA.LINE_LOCATION_ID = PLLA.LINE_LOCATION_ID
         AND PDA.PO_LINE_ID = PLA.PO_LINE_ID
         AND PLA.PO_LINE_ID = AILA.PO_LINE_ID
         AND PLA.PO_LINE_ID = RT.PO_LINE_ID                                     
         AND AIDA.PO_DISTRIBUTION_ID = PDA.PO_DISTRIBUTION_ID
         AND AILA.INVOICE_ID = AIA.INVOICE_ID
         AND AIPA.INVOICE_ID = AIA.INVOICE_ID
         AND ACA.CHECK_ID = AIPA.CHECK_ID
         AND PHA.CREATED_BY = FU.USER_ID
         AND AILA.RCV_TRANSACTION_ID = RT.TRANSACTION_ID
         AND PLA.ITEM_ID = MSIK.INVENTORY_ITEM_ID
         AND HOU.ORGANIZATION_ID = MSIK.ORGANIZATION_ID
         AND (PHA.SEGMENT1 = :PO_NUMBER OR :PO_NUMBER IS NULL)
         AND (AIA.INVOICE_NUM = :INVOICE_NUMBER OR :INVOICE_NUMBER IS NULL)
         AND (MSIK.INVENTORY_ITEM_ID = :ITEM_ID OR :ITEM_ID IS NULL)
         AND (MSIK.concatenated_segments = :ITEM_CODE OR :ITEM_CODE IS NULL)
         AND RT.TRANSACTION_TYPE = 'RECEIVE'
         AND (MSIK.ORGANIZATION_ID = :ORGANIZATION_ID OR :ORGANIZATION_ID IS NULL);         --101
/         
         
         --summation
SELECT PHA.CURRENCY_CODE||' '||ROUND(NVL (PLA.UNIT_PRICE, 0),2) AS "ITEM RATE",
         PHA.CURRENCY_CODE||' '||ROUND (NVL (PLA.UNIT_PRICE, 0) * NVL (PLA.QUANTITY, 0)) AS "PO VALUE",
          AIA.INVOICE_CURRENCY_CODE||' '||NVL (AILA.AMOUNT, 0) AS "INVOICE AMOUNT"
FROM  PO_HEADERS_ALL              PHA,
         PO_LINES_ALL                PLA,
         PO_LINE_LOCATIONS_ALL       PLLA,
         PO_DISTRIBUTIONS_ALL        PDA,
         RCV_TRANSACTIONS            RT,
         AP_INVOICE_DISTRIBUTIONS_ALL AIDA,
         AP_INVOICE_LINES_ALL        AILA,
         AP_INVOICES_ALL             AIA,
         AP_INVOICE_PAYMENTS_ALL     AIPA,
         AP_CHECKS_ALL               ACA,
         FND_USER                    FU,
         MTL_SYSTEM_ITEMS_KFV MSIK,
         HR_OPERATING_UNITS HOU
   WHERE     PHA.PO_HEADER_ID = PLA.PO_HEADER_ID
         AND PLLA.PO_LINE_ID = PLA.PO_LINE_ID
         AND PDA.LINE_LOCATION_ID = PLLA.LINE_LOCATION_ID
         AND PDA.PO_LINE_ID = PLA.PO_LINE_ID
         AND PLA.PO_LINE_ID = AILA.PO_LINE_ID
         AND PLA.PO_LINE_ID = RT.PO_LINE_ID                                     
         AND AIDA.PO_DISTRIBUTION_ID = PDA.PO_DISTRIBUTION_ID
         AND AILA.INVOICE_ID = AIA.INVOICE_ID
         AND AIPA.INVOICE_ID = AIA.INVOICE_ID
         AND ACA.CHECK_ID = AIPA.CHECK_ID
         AND PHA.CREATED_BY = FU.USER_ID
         AND AILA.RCV_TRANSACTION_ID = RT.TRANSACTION_ID
         AND PLA.ITEM_ID = MSIK.INVENTORY_ITEM_ID
         AND HOU.ORGANIZATION_ID = MSIK.ORGANIZATION_ID
         AND (PHA.SEGMENT1 = :PO_NUMBER OR :PO_NUMBER IS NULL)
         AND (AIA.INVOICE_NUM = :INVOICE_NUMBER OR :INVOICE_NUMBER IS NULL)
         AND (MSIK.INVENTORY_ITEM_ID = :ITEM_ID OR :ITEM_ID IS NULL)
         AND (MSIK.concatenated_segments = :ITEM_CODE OR :ITEM_CODE IS NULL)
         AND RT.TRANSACTION_TYPE = 'RECEIVE'
         AND (MSIK.ORGANIZATION_ID = :ORGANIZATION_ID OR :ORGANIZATION_ID IS NULL);
         /