--finding out a user made purchase order 
SELECT distinct *
FROM PO_HEADERS_ALL PHA, FND_USER FU
WHERE PHA.CREATED_BY = FU.USER_ID
AND UPPER(FU.USER_NAME) = UPPER(:P_USERNAME)
ORDER BY PHA.LAST_UPDATE_DATE DESC;