SELECT DISTINCT
    PHA.SEGMENT1 AS "PO NUMBER",
    APS.VENDOR_NAME AS "SUPPLIER",
    MSIK.concatenated_segments AS "ITEM CODE",
    PLA.QUANTITY AS "QUANTITY"
FROM
    PO_HEADERS_ALL PHA
    JOIN PO_LINES_ALL PLA ON PHA.PO_HEADER_ID = PLA.PO_HEADER_ID
    JOIN MTL_SYSTEM_ITEMS_KFV MSIK ON PLA.ITEM_ID = MSIK.INVENTORY_ITEM_ID
    JOIN HR_OPERATING_UNITS HOU ON HOU.ORGANIZATION_ID = MSIK.ORGANIZATION_ID
    JOIN AP_SUPPLIERS APS ON PHA.VENDOR_ID = APS.VENDOR_ID
WHERE
    (PHA.SEGMENT1 = :PO_NUMBER OR :PO_NUMBER IS NULL)
    AND (MSIK.INVENTORY_ITEM_ID = :ITEM_ID OR :ITEM_ID IS NULL)
    AND (MSIK.concatenated_segments = :ITEM_CODE OR :ITEM_CODE IS NULL)
    AND (MSIK.ORGANIZATION_ID = :ORGANIZATION_ID OR :ORGANIZATION_ID IS NULL)
    AND (upper(APS.VENDOR_NAME) LIKE '%'||Upper(:VENDOR_NAME)||'%' OR :VENDOR_NAME IS NULL)
    AND PHA.ATTRIBUTE1 LIKE 'I%'
--    AND ROWNUM < 100; -- Limit by 100 rows
