SELECT DISTINCT
    pha.org_id,
    hou.NAME,
    PHA.PO_HEADER_ID,
    PHA.SEGMENT1                   AS "PO NUMBER",
    pha.AUTHORIZATION_STATUS,
    pha.creation_date,
    pha.APPROVED_DATE,
    pha.CLOSED_DATE,
    PHA.CLOSED_CODE,
    APS.VENDOR_NAME                AS "SUPPLIER",
    MSIK.concatenated_segments     AS "ITEM CODE",
    MSIK.DESCRIPTION,
    PLA.QUANTITY                   AS "QUANTITY",
    pha.currency_code,
    PLA.UNIT_PRICE,
    RT.TRANSACTION_TYPE, RT.TRANSACTION_DATE, RT.PRIMARY_QUANTITY, RT.ATTRIBUTE15,
    (nvl(PLA.QUANTITY,0)  - nvl(RT.PRIMARY_QUANTITY,0)) po_rcv_difference
FROM
    PO_HEADERS_ALL      PHA,
    PO_LINES_ALL        PLA,
    MTL_SYSTEM_ITEMS_KFV MSIK,
    HR_OPERATING_UNITS  HOU,
    AP_SUPPLIERS        APS,
    RCV_TRANSACTIONS    RT 
WHERE PHA.PO_HEADER_ID = PLA.PO_HEADER_ID
AND PLA.ITEM_ID = MSIK.INVENTORY_ITEM_ID
AND pha.org_id = HOU.ORGANIZATION_ID AND pLa.org_id = HOU.ORGANIZATION_ID
AND PHA.PO_HEADER_ID = RT.PO_HEADER_ID
AND PHA.VENDOR_ID = APS.VENDOR_ID
AND PLA.PO_LINE_ID = RT.PO_LINE_ID
  AND pha.creation_date > '31-MAY-23'
    AND PHA.ATTRIBUTE1 LIKE 'I%'
    AND (pha.org_id = :ORGANIZATION_ID OR :ORGANIZATION_ID IS NULL)
    AND (PHA.SEGMENT1  = :PO_NUMBER OR :PO_NUMBER IS NULL)
    AND RT.TRANSACTION_TYPE = 'DELIVER'  -- Add this condition
ORDER BY
MSIK.concatenated_segments,   PHA.ORG_ID, PHA.SEGMENT1, pha.creation_date;
