SELECT PR_NO,PR_CREATE_DATE,PR_TYPE,PR_CREATE_BY,ITEM_CODE,ITEM_DESCRIPTION,CATAGORY,UOM,PR_QTY,PO_QUANTITY,
PO_NO,PO_CREATE_DATE,BUYER_NAME,SUPPLIER_NAME,MRR_NO,MRR_QTY,MRR_DATE,PO_PENDING,CURRENCY_CODE,UNIT_PRICE FROM
(SELECT PRH.SEGMENT1 PR_NO,
         PRH.CREATION_DATE PR_CREATE_DATE,
         PRH.ATTRIBUTE11 PR_TYPE,
         PRH.CREATED_BY PR_CREATE_BY,
         (SELECT DISTINCT CONCATENATED_SEGMENTS
            FROM MTL_SYSTEM_ITEMS_KFV
           WHERE INVENTORY_ITEM_ID = PRL.ITEM_ID)
            ITEM_CODE,
          (SELECT DISTINCT SEGMENT1 FROM   MTL_ITEM_CATEGORIES_V WHERE INVENTORY_ITEM_ID= POL.ITEM_ID 
          AND ORGANIZATION_ID=POLL.SHIP_TO_ORGANIZATION_ID) CATAGORY,
         PRL.ITEM_DESCRIPTION ITEM_DESCRIPTION,
         PRL.UNIT_MEAS_LOOKUP_CODE UOM,
         PRL.QUANTITY PR_QTY,
         NVL (POL.QUANTITY, '') PO_QUANTITY,
         POH.SEGMENT1 PO_NO,
         POH.CREATION_DATE PO_CREATE_DATE,
         GET_BUYER_NAME (POH.AGENT_ID) BUYER_NAME,
         (SELECT DISTINCT VENDOR_NAME
            FROM AP_SUPPLIERS
           WHERE VENDOR_ID = POH.VENDOR_ID)
            SUPPLIER_NAME,
         XX_MRR_NO (PDA.PO_HEADER_ID, PDA.PO_LINE_ID) MRR_NO,
         XX_MRR_QTY (PDA.PO_HEADER_ID, PDA.PO_LINE_ID) MRR_QTY,
         TO_CHAR (TRUNC (GET_MRR_DATE (PDA.PO_HEADER_ID)), 'DD-MON-RRRR')
            MRR_DATE,
         PRL.QUANTITY - NVL (POL.QUANTITY, 0) PO_PENDING,
         POH.CURRENCY_CODE,
         TO_CHAR ( (NVL (ROUND (POL.UNIT_PRICE, 2), '')), 'fM99G999D00')
            UNIT_PRICE
    FROM PO_REQUISITION_HEADERS_ALL PRH,
         PO_REQUISITION_LINES_ALL PRL,
         PO_REQ_DISTRIBUTIONS_ALL PRD,
         --per_people_x ppx,
         PO_HEADERS_ALL POH,
         PO_LINES_ALL POL,
         PO_DISTRIBUTIONS_ALL PDA,
         (  SELECT SHIP_TO_ORGANIZATION_ID,
                   PO_LINE_ID,
                   SUM (NVL (QUANTITY_RECEIVED, 0)) QUANTITY_RECEIVED
              FROM PO_LINE_LOCATIONS_ALL
          GROUP BY SHIP_TO_ORGANIZATION_ID, PO_LINE_ID) POLL
   WHERE     PRH.REQUISITION_HEADER_ID = PRL.REQUISITION_HEADER_ID
         --AND ppx.person_id = prh.preparer_id
         AND PRH.TYPE_LOOKUP_CODE = 'PURCHASE'
         AND PRD.REQUISITION_LINE_ID = PRL.REQUISITION_LINE_ID
         AND PDA.REQ_DISTRIBUTION_ID(+) = PRD.DISTRIBUTION_ID
         AND PDA.PO_HEADER_ID = POH.PO_HEADER_ID(+)
         AND PDA.PO_HEADER_ID = POH.PO_HEADER_ID(+)
         AND PDA.PO_LINE_ID = POL.PO_LINE_ID(+)
         AND POL.PO_LINE_ID = POLL.PO_LINE_ID(+)
         AND TRUNC (PRH.CREATION_DATE) BETWEEN NVL ( :P_F_DT,
                                                    TRUNC (PRH.CREATION_DATE))
                                           AND NVL ( :P_T_DT,
                                                    TRUNC (PRH.CREATION_DATE))
         AND (:P_CREATE_BY IS NULL OR PRH.CREATED_BY=:P_CREATE_BY)
         AND ( :P_ORG_ID IS NULL OR PRH.ORG_ID = :P_ORG_ID)
         AND ( :P_PO_TYPE IS NULL OR POH.ATTRIBUTE1 = :P_PO_TYPE)
         AND ( :P_SUP IS NULL OR POH.VENDOR_ID = :P_SUP)
         AND (   :P_BUYER_NAME IS NULL
              OR GET_BUYER_NAME (POH.AGENT_ID) = :P_BUYER_NAME)
         AND (   :P_REQ_DEPT IS NULL
              OR GET_REQ_DEPT (PRH.REQUISITION_HEADER_ID) = :P_REQ_DEPT)
         AND ( :P_PR_TYPE IS NULL OR PRH.ATTRIBUTE11 = :P_PR_TYPE)
         AND PRH.ATTRIBUTE11 IN ('Local', 'Import')
         AND PRH.AUTHORIZATION_STATUS = 'APPROVED'
         AND PRH.CANCEL_FLAG IS NULL)
    WHERE (:P_ITEM_CODE IS NULL OR ITEM_CODE  = :P_ITEM_CODE)
    AND (:P_CATAGORY IS NULL OR CATAGORY  = :P_CATAGORY)
    and PO_NO is null
    and pr_no = '11809233'
ORDER BY PR_CREATE_DATE DESC;
/