SELECT PRH.ORG_ID,
       PRH.REQUISITION_HEADER_ID,
       PRH.SEGMENT1       PR_NUMBER,
       PRH.CREATION_DATE,PRH.CREATED_BY,
       XX_COM_PKG.GET_USER_NAME (PRH.CREATED_BY) CREATED_BY,
       PRH.ATTRIBUTE1     DEPARTMENT,
       PRH.AUTHORIZATION_STATUS,
       PRH.APPROVED_DATE,
       ROUND(PRH.APPROVED_DATE-PRH.CREATION_DATE) DELAY,
       PRL.ITEM_ID,MSI.CONCATENATED_SEGMENTS,
       PRL.ITEM_DESCRIPTION,
       PRL.UNIT_MEAS_LOOKUP_CODE,
       PRL.QUANTITY,
       PRL.QUANTITY_DELIVERED
  FROM PO.PO_REQUISITION_HEADERS_ALL  PRH,
       PO.PO_REQUISITION_LINES_ALL    PRL,
       MTL_SYSTEM_ITEMS_KFV MSI
        WHERE PRH.REQUISITION_HEADER_ID = PRL.REQUISITION_HEADER_ID
        AND  PRL.ITEM_ID=MSI.INVENTORY_ITEM_ID
        AND trunc(PRH.CREATION_DATE) BETWEEN '01-JAN-24' AND '29-FEB-24'
        AND PRH.ORG_ID=105