SELECT lpad(OU_CODE,5)OU_CODE,WAREHOUSE_CODE,MOTHER_CAT, 
SUM(DO_AMOUNT) DO_AMOUNT, SUM(DEL_AMT) DEL_AMT, SUM(UNCR_AMT) UNCR_AMT,SUM(UNCS_AMT) UNCS_AMT  FROM 
(---------------------------DO Amount------------------------------

SELECT to_char(OOD.ORGANIZATION_CODE) OU_CODE,OOD.ORGANIZATION_NAME WAREHOUSE_CODE,
        KFV.ATTRIBUTE10 MOTHER_CAT,
        ROUND(((OL.ORDERED_QUANTITY*OL. UNIT_SELLING_PRICE)),2) DO_AMOUNT,
        TO_NUMBER(0) DEL_AMT,
        TO_NUMBER(0) UNCR_AMT,
        TO_NUMBER(0) UNCS_AMT
      --  ,CUST.CUSTOMER_NUMBER
 FROM 
          XX_OE_ORDER_HEADERS_V OH,
          XX_AR_CUSTOMERS_ALL_V CUST,
          MTL_SYSTEM_ITEMS_KFV KFV,
          HR_OPERATING_UNITS HR,
          XX_OE_ORDER_LINES_V  OL,
          MTL_ITEM_CATEGORIES MIC,
          MTL_CATEGORIES MC,
          ORG_ORGANIZATION_DEFINITIONS OOD
WHERE 
         OL.INVENTORY_ITEM_ID=KFV.INVENTORY_ITEM_ID
     AND KFV.ORGANIZATION_ID=OL.SHIP_FROM_ORG_ID
     AND OOD.ORGANIZATION_ID=OL.SHIP_FROM_ORG_ID
     AND OH.HEADER_ID=OL.HEADER_ID
     AND OH.SOLD_TO_ORG_ID = CUST.CUSTOMER_ID
     AND MIC.ORGANIZATION_ID = KFV.ORGANIZATION_ID
     AND MIC.INVENTORY_ITEM_ID = KFV.INVENTORY_ITEM_ID
     AND MIC.CATEGORY_ID = MC.CATEGORY_ID
     AND MC.STRUCTURE_ID = 101
     AND TRUNC(OH.ORDERED_DATE) BETWEEN  NVL(:P_F_DT, TRUNC(OH.ORDERED_DATE)) AND NVL(:P_T_DT, TRUNC(OH.ORDERED_DATE))            
     AND HR.ORGANIZATION_ID = OH.ORG_ID
     AND (:P_WH IS NULL OR OOD.ORGANIZATION_CODE=:P_WH)
     AND OH.ORG_ID=:P_ORG
     AND OH.ORDER_TYPE_ID NOT IN ('1182', '1184')
     AND UPPER(OL.FLOW_STATUS_CODE)<>'CANCELLED'
--     AND (:P_WH is null or OL.SHIP_FROM_ORG_ID=:P_WH)
    AND (:P_MCAT IS NULL OR KFV.ATTRIBUTE10 = :P_MCAT)
     AND OH.ORDER_CATEGORY_CODE IN ('ORDER', 'MIXED')
     AND OL.LINE_CATEGORY_CODE IN ('ORDER', 'MIXED')
     AND OH.FLOW_STATUS_CODE IN ('BOOKED','CLOSED')
     AND OL.LINE_CATEGORY_CODE<>'RETURN'
     AND CUST.CUSTOMER_CLASS_CODE NOT IN ('INTERCOMPANY')
     and (:P_CUSTOMER_ID IS NULL OR CUST.CUSTOMER_ID = :P_CUSTOMER_ID)
  
UNION ALL
------------------------------Sales Amount--------------------------------
 SELECT to_char(SAL.WAREHOUSE_ID) OU_CODE,
 (SELECT ORGANIZATION_NAME FROM ORG_ORGANIZATION_DEFINITIONS WHERE ORGANIZATION_ID=SAL.WAREHOUSE_ID)WAREHOUSE_CODE, 
  KFV.ATTRIBUTE10 MOTHER_CAT,
            TO_NUMBER(0) DO_AMOUNT,
             (NVL(DR_AMOUNT,0)) DEL_AMT,
            TO_NUMBER(0) UNCR_AMT,
            TO_NUMBER(0) UNCS_AMT
            --  ,CUST.CUSTOMER_NUMBER
 FROM XX_AR_CUST_DTL_LED_ACTUAL_V10 SAL,
        MTL_SYSTEM_ITEMS_KFV KFV,
        MTL_ITEM_CATEGORIES MIC,
        MTL_CATEGORIES MC,
        XX_AR_CUSTOMERS_ALL_V CUST
 WHERE SAL.CUSTOMER_ID=CUST.CUSTOMER_ID(+)
        AND TRX_TYPE IN ('Sales')
        AND SAL.INVENTORY_ITEM_ID = KFV.INVENTORY_ITEM_ID 
        AND SAL.WAREHOUSE_ID= KFV.ORGANIZATION_ID
        AND MIC.ORGANIZATION_ID = KFV.ORGANIZATION_ID
        AND MIC.INVENTORY_ITEM_ID = KFV.INVENTORY_ITEM_ID
        AND MIC.CATEGORY_ID = MC.CATEGORY_ID
        AND MC.STRUCTURE_ID = 101
        AND (:P_ORG IS NULL OR SAL.ORG_ID=:P_ORG)
        AND (:P_WH IS NULL OR SAL.WAREHOUSE_ID=:P_WH)
        AND TRUNC (GL_DATE) BETWEEN :P_F_DT AND :P_T_DT
        AND (:P_MCAT IS NULL OR KFV.ATTRIBUTE10 = :P_MCAT)
        AND CUST.CUSTOMER_CLASS_CODE NOT IN ('INTERCOMPANY')
        and (:P_CUSTOMER_ID IS NULL OR CUST.CUSTOMER_ID = :P_CUSTOMER_ID)

UNION ALL
----------------------------Undelivered Credit Amount------------------------------------------------------
SELECT to_char(OOD.ORGANIZATION_CODE) OU_CODE,OOD.ORGANIZATION_NAME WAREHOUSE_CODE,
KFV.ATTRIBUTE10 MOTHER_CAT,
         TO_NUMBER(0) DO_AMOUNT,
         TO_NUMBER(0) DEL_AMT, 
          (((OL.ORDERED_QUANTITY-NVL(OL.CANCELLED_QUANTITY,0)-NVL(OL.SHIPPED_QUANTITY,0)))*OL.UNIT_SELLING_PRICE) UNCR_AMT,
         TO_NUMBER(0) UNCS_AMT
         --  ,CUST.CUSTOMER_NUMBER
FROM  XX_OE_ORDER_HEADERS_V OH,
        XX_AR_CUSTOMERS_ALL_V CUST,
        XX_OE_ORDER_LINES_V  OL,
        MTL_SYSTEM_ITEMS_KFV KFV,
        MTL_ITEM_CATEGORIES MIC,
        MTL_CATEGORIES MC,
        ORG_ORGANIZATION_DEFINITIONS OOD
WHERE OH.HEADER_ID=OL.HEADER_ID
  AND OH.ORG_ID=OL.ORG_ID
  AND OH.SOLD_TO_ORG_ID = CUST.CUSTOMER_ID
  AND  OL.INVENTORY_ITEM_ID(+)=KFV.INVENTORY_ITEM_ID
  AND KFV.ORGANIZATION_ID=OL.SHIP_FROM_ORG_ID
  AND MIC.ORGANIZATION_ID = KFV.ORGANIZATION_ID
  AND OOD.ORGANIZATION_ID=OL.SHIP_FROM_ORG_ID
  AND MIC.INVENTORY_ITEM_ID = KFV.INVENTORY_ITEM_ID
  AND MIC.CATEGORY_ID = MC.CATEGORY_ID
  AND MC.STRUCTURE_ID = 101
  AND OH.ORDER_CATEGORY_CODE IN ('ORDER', 'MIXED')
  AND OL.LINE_CATEGORY_CODE IN ('ORDER', 'MIXED')
  AND OH.FLOW_STATUS_CODE IN ('BOOKED','CLOSED')
  AND NVL(XXPAY_TYPE_CODE(OH.HEADER_ID),OH.PAYMENT_TYPE_CODE) IS NULL
  AND UPPER(OL.FLOW_STATUS_CODE)<>'CANCELLED'
  AND OH.ORDER_TYPE_ID NOT IN ('1182','1184')
  AND CUST.CUSTOMER_CLASS_CODE NOT IN ('INTERCOMPANY')
  AND(TRUNC(OH.ORDERED_DATE) BETWEEN (TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,-1))+1)) AND (TRUNC(SYSDATE))) 
  AND OH.ORG_ID=:P_ORG
  AND (:P_WH IS NULL OR OOD.ORGANIZATION_CODE=:P_WH)
  AND (:P_MCAT IS NULL OR KFV.ATTRIBUTE10 = :P_MCAT)
  and (:P_CUSTOMER_ID IS NULL OR CUST.CUSTOMER_ID = :P_CUSTOMER_ID)

UNION ALL
-----------------------------undelivered Cash Amount-----------------------------
 SELECT to_char(OOD.ORGANIZATION_CODE) OU_CODE,OOD.ORGANIZATION_NAME WAREHOUSE_CODE,
 KFV.ATTRIBUTE10 MOTHER_CAT,   
         TO_NUMBER(0) DO_AMOUNT,
         TO_NUMBER(0) DEL_AMT,
         TO_NUMBER(0) UNCR_AMT,
         (((OL.ORDERED_QUANTITY-NVL(OL.CANCELLED_QUANTITY,0)-NVL(OL.SHIPPED_QUANTITY,0)))*OL.UNIT_SELLING_PRICE) UNCS_AMT
         --  ,CUST.CUSTOMER_NUMBER
FROM XX_OE_ORDER_HEADERS_V OH,
       XX_AR_CUSTOMERS_ALL_V CUST,
       XX_OE_ORDER_LINES_V  OL,
       MTL_SYSTEM_ITEMS_KFV KFV,
       MTL_ITEM_CATEGORIES MIC,
       MTL_CATEGORIES MC,
       ORG_ORGANIZATION_DEFINITIONS OOD
WHERE OH.HEADER_ID=OL.HEADER_ID
   AND OH.ORG_ID=OL.ORG_ID
   AND OH.SOLD_TO_ORG_ID = CUST.CUSTOMER_ID
  AND  OL.INVENTORY_ITEM_ID(+)=KFV.INVENTORY_ITEM_ID
  AND KFV.ORGANIZATION_ID=OL.SHIP_FROM_ORG_ID
  AND MIC.ORGANIZATION_ID = KFV.ORGANIZATION_ID
  AND MIC.INVENTORY_ITEM_ID = KFV.INVENTORY_ITEM_ID
  AND MIC.CATEGORY_ID = MC.CATEGORY_ID
  AND OOD.ORGANIZATION_ID=OL.SHIP_FROM_ORG_ID
  AND MC.STRUCTURE_ID = 101
  AND OH.ORDER_CATEGORY_CODE IN ('ORDER', 'MIXED')
  AND OL.LINE_CATEGORY_CODE IN ('ORDER', 'MIXED')
  AND OH.FLOW_STATUS_CODE IN ('BOOKED','CLOSED')
  AND NVL(XXPAY_TYPE_CODE(OH.HEADER_ID),OH.PAYMENT_TYPE_CODE) IN ('CASH','CHECK','Credit Card') 
  AND UPPER(OL.FLOW_STATUS_CODE)<>'CANCELLED'
  AND OH.ORDER_TYPE_ID NOT IN ('1182','1184')
  AND CUST.CUSTOMER_CLASS_CODE NOT IN ('INTERCOMPANY')
  AND(TRUNC(OH.ORDERED_DATE) BETWEEN (TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,-2))+1)) AND (TRUNC(SYSDATE))) 
  AND OH.ORG_ID=:P_ORG
  AND (:P_WH IS NULL OR OOD.ORGANIZATION_CODE=:P_WH)
  AND (:P_MCAT IS NULL OR KFV.ATTRIBUTE10 = :P_MCAT)
  and (:P_CUSTOMER_ID IS NULL OR CUST.CUSTOMER_ID = :P_CUSTOMER_ID)     --XX_CUSTOMER_NUMBER_NEW
  ) --where OU_CODE=101
 GROUP BY OU_CODE,WAREHOUSE_CODE,MOTHER_CAT
 ORDER BY lpad(OU_CODE,5);