DECLARE
V__USERNAME VARCHAR2(3000) := :username;
BEGIN
FOR i IN (SELECT SID, SERIAL# srl, STATUS, SERVER
FROM V$SESSION
WHERE UPPER(USERNAME) = UPPER(V__USERNAME)) LOOP

EXECUTE IMMEDIATE 'ALTER SYSTEM KILL SESSION '||i.sid||', '||i.srl;

END LOOP;

END;
/
