SELECT TRIM(UPPER(PRD_ITEM))
FROM XX_FORMULA_UPLOAD
WHERE ORG_CODE = 110
MINUS
SELECT TRIM(UPPER(CONCATENATED_SEGMENTS))
FROM MTL_SYSTEM_ITEMS_KFV;
--WHERE ORGANIZATION_ID = 101
-----------------------------------
SELECT TRIM(UPPER(ING_ITEM_CODE))
FROM XX_FORMULA_UPLOAD
WHERE ORG_CODE = 110
MINUS
SELECT TRIM(UPPER(CONCATENATED_SEGMENTS))
FROM MTL_SYSTEM_ITEMS_KFV;
--WHERE ORGANIZATION_ID = 101




SELECT TRIM(UPPER(PRD_ITEM))
FROM XX_FORMULA_UPLOAD
WHERE ORG_CODE = 210
MINUS
SELECT TRIM(UPPER(CONCATENATED_SEGMENTS))
FROM MTL_SYSTEM_ITEMS_KFV;
--WHERE ORGANIZATION_ID = 102
-----------------------------------
SELECT TRIM(UPPER(ING_ITEM_CODE))
FROM XX_FORMULA_UPLOAD
WHERE ORG_CODE = 210
MINUS
SELECT TRIM(UPPER(CONCATENATED_SEGMENTS))
FROM MTL_SYSTEM_ITEMS_KFV;
--WHERE ORGANIZATION_ID = 102

UPDATE XX_FORMULA_UPLOAD
SET ING_ITEM_CODE = 'ADDT.MBPBL.502'
WHERE ING_ITEM_CODE = 'ADDT.MBPBl.502'

COMMIT;

select *
from xx_formula_upload
where ing_item_code = 'RAW.ACC.011'
and org_code = 110;


SELECT LENGTH(SUBSTR('015.254.235',1,INSTR('015.254.235','.',1,1)-1)) --IF LESS THEN 3 THEN ADD 0 INITIATE
FROM DUAL;


SELECT LENGTH(SUBSTR(TRIM(PRD_ITEM),1,INSTR(TRIM(PRD_ITEM),'.',1,1)-1)) --IF LESS THEN 3 THEN ADD 0 INITIATE
FROM DUAL;


SELECT 0||'015.254.235'
FROM DUAL;

SELECT 0||TRIM(PRD_ITEM)
FROM DUAL;



SELECT CASE AB < 3 THEN ADD 0
ELSE AB END


SELECT INSTR('015.254.235','.',1,1)
FROM DUAL;




SELECT CASE WHEN LENGTH(SUBSTR(TRIM(PRD_ITEM),1,INSTR(TRIM(PRD_ITEM),'.',1,1)-1)) < 3 
                THEN 0||TRIM(PRD_ITEM)
ELSE TRIM(PRD_ITEM)
END PRD_ITEM
FROM XX_FORMULA_UPLOAD
WHERE ORG_CODE = 210
MINUS
SELECT TRIM(CONCATENATED_SEGMENTS)
FROM MTL_SYSTEM_ITEMS_KFV;
--WHERE ORGANIZATION_ID = 102
-----------------------------------
SELECT 
CASE WHEN LENGTH(SUBSTR(TRIM(ING_ITEM_CODE),1,INSTR(TRIM(ING_ITEM_CODE),'.',1,1)-1)) < 3 
                THEN 0||TRIM(ING_ITEM_CODE)
ELSE TRIM(ING_ITEM_CODE)
END ING_ITEM_CODE
FROM XX_FORMULA_UPLOAD
WHERE ORG_CODE = 210
MINUS
SELECT TRIM(CONCATENATED_SEGMENTS)
FROM MTL_SYSTEM_ITEMS_KFV;
--WHERE ORGANIZATION_ID = 102